<a href="https://colab.research.google.com/github/Batatoni/Teste/blob/main/Aulas_Alunos_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SEMANA 01

# SEMANA 02

Como um rover autônomo pode utilizar Machine Learning para continuar mapeando um terreno desconhecido de forma segura quando seus sensores principais sofrem falhas críticas durante uma missão de bilhoes de dólares?

In [132]:
# Bibliotecas
import numpy as np # Gerar números
from sklearn.tree import DecisionTreeClassifier # Classificação - "cérebro" do rover
from sklearn.metrics import accuracy_score # Acurácia

In [133]:
# Parte 1: Simulação do Terreno Marciano
np.random.seed(42) # Configuração de padrão dos dados
terreno_treino = np.random.rand(1000,3) # 0.0 a 1.0

In [134]:
terreno_treino

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       ...,
       [0.80000348, 0.55270708, 0.39655368],
       [0.13171503, 0.86529576, 0.15727321],
       [0.30978786, 0.29004553, 0.87141403]])

In [135]:
# Regra de Perigo: Inclinação + Rugosidade > 1.2, o terreno é perigoso (1), senão é seguro
# Radiação (0) / Inclinação (1) / Rugosidade (2)
status_treino = (terreno_treino[:,1] + terreno_treino[:,2] > 1.2).astype(int)

In [136]:
terreno_treino

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       ...,
       [0.80000348, 0.55270708, 0.39655368],
       [0.13171503, 0.86529576, 0.15727321],
       [0.30978786, 0.29004553, 0.87141403]])

In [137]:
import pandas as pd
df_treino = pd.DataFrame(terreno_treino, columns=['Radiação', 'Inclinação', 'Rugosidade'])
df_treino['Status'] = status_treino
df_treino

Radiação  Inclinação  Rugosidade  Status
0    0.374540    0.950714    0.731994       1
1    0.598658    0.156019    0.155995       0
2    0.058084    0.866176    0.601115       1
3    0.708073    0.020584    0.969910       0
4    0.832443    0.212339    0.181825       0
..        ...         ...         ...     ...
995  0.967035    0.051669    0.504796       0
996  0.718454    0.862640    0.179256       0
997  0.800003    0.552707    0.396554       0
998  0.131715    0.865296    0.157273       0
999  0.309788    0.290046    0.871414       0

[1000 rows x 4 columns]

In [138]:
status_treino

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,

In [139]:
# Parte 2: Treinamento
# Criando o modelo
cerebro_rover = DecisionTreeClassifier(max_depth=4)

In [140]:
cerebro_rover # Modelo não está treinado

DecisionTreeClassifier(max_depth=4)

In [141]:
# Treinar o modelo
cerebro_rover.fit(terreno_treino, status_treino)
print("Modelo Treinado")

Modelo Treinado


In [142]:
cerebro_rover

DecisionTreeClassifier(max_depth=4)

In [143]:
# Parte 3: Simulação de Operação Normal e Falha Crítica

In [144]:
terreno_novo = np.random.rand(200,3)

In [145]:
# Calcula o status real desse novo terreno para podermos comparar depois
status_real = (terreno_novo[:,1] + terreno_novo[:,2] > 1.2).astype(int)

In [146]:
previsao_normal = cerebro_rover.predict(terreno_novo)
acuracia_normal = accuracy_score(status_real, previsao_normal)
print(f"Acurácia no Terreno Normal: {acuracia_normal * 100:.2f}%")

Acurácia no Terreno Normal: 93.00%


In [147]:
terreno_com_falha = terreno_novo.copy()
terreno_com_falha[:,1] = 0.0


In [148]:
previsao_falha = cerebro_rover.predict(terreno_com_falha)
acuracia_falha = accuracy_score(status_real, previsao_falha)
print(f"Acurácia no Terreno com Falha Crítica: {acuracia_falha * 100:.2f}%")


Acurácia no Terreno com Falha Crítica: 64.00%


In [149]:
perda = (acuracia_normal - acuracia_falha) * 100
print(f"Risco financeiro/missão: Houve uma queda de {perda:.1f}% na segurança.")

Risco financeiro/missão: Houve uma queda de 29.0% na segurança.


In [150]:
import numpy as np

terreno_treino_emergencia = terreno_treino[:, [0, 2]]
print("Novo conjunto de treinamento criado: terreno_treino_emergencia_sem_inclinacao")

Novo conjunto de treinamento criado: terreno_treino_emergencia_sem_inclinacao


In [151]:
from sklearn.tree import DecisionTreeClassifier

# 1. Definir status_treino_emergencia a partir do terreno_treino_emergencia original (3 colunas)
status_treino_emergencia = (terreno_treino_emergencia[:,0] + terreno_treino_emergencia[:,1] > 1.2).astype(int)

# 2. Criar uma nova instância de DecisionTreeClassifier
cerebro_emergencia = DecisionTreeClassifier(max_depth=4)

# 3. Treinar o modelo cerebro_emergencia
cerebro_emergencia.fit(terreno_treino_emergencia, status_treino_emergencia)

print("Modelo cerebro_emergencia treinado com sucesso!")

Modelo cerebro_emergencia treinado com sucesso!


In [152]:


# 1. Calcule a média das leituras da coluna de 'Inclinação' (coluna de índice 1) do array terreno_com_falha.
media_inclinacao = np.mean(terreno_com_falha[:, 1])

# 2. Implemente uma condição if para verificar se essa média é exatamente 0.0.
if media_inclinacao == 0.0:

    terreno_com_falha_sem_inclinacao = np.delete(terreno_com_falha, 1, axis=1)
    previsao_final = cerebro_emergencia.predict(terreno_com_falha_sem_inclinacao)
    print("Condição de falha detectada: Usando o modelo cerebro_emergencia para previsões.")
else:
    previsao_final = cerebro_rover.predict(terreno_com_falha)

    print("Nenhuma falha crítica detectada na inclinação: Usando o modelo cerebro_rover para previsões.")

print("Simulação de diagnóstico e previsão concluída.")

Condição de falha detectada: Usando o modelo cerebro_emergencia para previsões.
Simulação de diagnóstico e previsão concluída.


In [153]:

# Calcular a acurácia da previsão final
acuracia_final = accuracy_score(status_real, previsao_final)

# Apresentar as acurácias para comparação
print(f"Acurácia no Terreno Normal: {acuracia_normal * 100:.2f}%")
print(f"Acurácia no Terreno com Falha Crítica (Sem ML Adaptativo): {acuracia_falha * 100:.2f}%")
print(f"Acurácia com o Sistema de Decisão de Emergência: {acuracia_final * 100:.2f}%")

# Comparação
if acuracia_final > acuracia_falha:
    print(f"O sistema de emergência melhorou a acurácia em {(acuracia_final - acuracia_falha) * 100:.2f}% em relação à falha crítica.")
else:
    print(f"O sistema de emergência não melhorou a acurácia em relação à falha crítica.")

Acurácia no Terreno Normal: 93.00%
Acurácia no Terreno com Falha Crítica (Sem ML Adaptativo): 64.00%
Acurácia com o Sistema de Decisão de Emergência: 68.00%
O sistema de emergência melhorou a acurácia em 4.00% em relação à falha crítica.
